adjective = input("Enter any adjective: ")
adjective2 = input("Enter any adjective: ")
noun = input("Enter any noun: ")
noun2 = input("Enter any noun: ")
plural_noun = input("Enter a plural noun: ")
game = input("Enter any game: ")
plural_noun2 = input("Enter a plural noun: ")
verb_ending_in_ing = input("Enter any verb ending with ING: ")
verb_ending_in_ing2 = input("Enter any verb ending with ING: ")
plural_noun3 = input("Enter any Noun: ")
verb_ending_in_ing3 = input("Enter any verb ending with ING: ")
noun3 = input("Enter a noun: ")
plant = input("Enter any plant: ")
part_of_the_body = input("Enter any part of the body: ")
place = input("Enter any place: ")
verb_ending_in_ing4 = input("Enter any verb ending with ING: ")
adjective3 = input("Enter any adjective: ")
number = input("Enter any number: ")
plural_noun4 = input("Enter any plural noun: ")

print("A vacation is when you take a trip to some " + adjective)
print("with your " + adjective2 , " family." , " Usually you go to some place that is near a " +noun, " Or up a " +noun2)
print("A good vacation is one where you can ride " +plural_noun , " or play " +game , " or go hunting for "+plural_noun2)
print("I like spending my time "+verb_ending_in_ing , "or "+verb_ending_in_ing2)
print("When parent go on a vacation, they spend their time eating three "+plural_noun3 , " a day, and fathers play golf, and mothers sit around "+verb_ending_in_ing3)
print("Last summer, my little brother fell in a "+noun3 , " and got a poison "+plant, " all over his "+part_of_the_body)
print("My family is going to "+place, " , and I will practise"+verb_ending_in_ing4)
print("Parents need vacations more than kids because parents are always very "+adjective3, "and because they have to work "+number, "hours everyday all year making enough "+plural_noun4, "to pay fo the vacation.")